version: 2

jobs:
      build:
            docker:
            - image: circleci/php:7.1

            environment:
                  MODULE_DIR: app/code/Eadesigndev/Pdfgenerator

            working_directory: ~/magento

            steps:
            - run:
                    name: Setup test environment
                    command: |
                          sudo apt-get install -y libpng-dev
                          sudo docker-php-ext-install gd
                          sudo docker-php-ext-install bcmath
                          sudo apt-get install -y libmcrypt-dev
                          sudo docker-php-ext-install mcrypt
                          sudo apt-get install -y libxslt-dev
                          sudo docker-php-ext-install xsl
                          sudo docker-php-ext-install pdo_mysql
                          sudo docker-php-ext-install soap
            - run:
                    name: Setup composer details
                    command: |
                          sudo composer self-update
                          mkdir ~/.composer
                          touch ~/.composer/auth.json
                          echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_KEY}\",\"password\":\"${MAGENTO_SECRET}\"}}}" > ~/.composer/auth.json
                          composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition . 2.3
                          composer require eadesignro/module-eacore
                          composer require mpdf/mpdf

            - run: mkdir -p $MODULE_DIR
            - checkout:
                    path: $MODULE_DIR

            - run:
                    name: Install marketplace qulity tools
                    command: composer create-project --repository=https://repo.magento.com magento/marketplace-eqp magento-coding-standard

            - run:
                    name: Verifing the code with code sniffer
                    command: php magento-coding-standard/vendor/bin/phpcs --standard=magento-coding-standard/MEQP2/ruleset.xml --ignore=*/view/* app/code/Eadesigndev/Pdfgenerator/

            - run:
                    name: Verifing the code with mess detector
                    command: php vendor/bin/phpmd app/code/Eadesigndev/Pdfgenerator/ text dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml

            - run:
                    name: Enable all module
                    command: php bin/magento module:enable --all

            - run:
                    name: Run compilation
                    command: php -d memory_limit=6G bin/magento setup:di:compile

